class UsLocations {
  static const Map<String, List<String>> statesCities = {
    'Alabama': [
      'Birmingham',
      'Montgomery',
      'Huntsville',
      'Mobile',
      'Tuscaloosa',
    ],
    'Alaska': [
      'Anchorage',
      'Fairbanks',
      'Juneau',
    ],
    'Arizona': [
      'Phoenix',
      'Tucson',
      'Mesa',
      'Chandler',
      'Scottsdale',
      'Glendale',
      'Gilbert',
      'Tempe',
    ],
    'Arkansas': [
      'Little Rock',
      'Fort Smith',
      'Fayetteville',
      'Springdale',
      'Jonesboro',
    ],
    'California': [
      'Los Angeles',
      'San Diego',
      'San Jose',
      'San Francisco',
      'Fresno',
      'Sacramento',
      'Long Beach',
      'Oakland',
    ],
    'Colorado': [
      'Denver',
      'Colorado Springs',
      'Aurora',
      'Fort Collins',
      'Lakewood',
      'Thornton',
    ],
    'Connecticut': [
      'Bridgeport',
      'New Haven',
      'Stamford',
      'Hartford',
      'Waterbury',
    ],
    'Delaware': [
      'Wilmington',
      'Dover',
      'Newark',
    ],
    'District of Columbia': [
      'Washington',
    ],
    'Florida': [
      'Jacksonville',
      'Miami',
      'Tampa',
      'Orlando',
      'St. Petersburg',
      'Hialeah',
      'Tallahassee',
      'Fort Lauderdale',
    ],
    'Georgia': [
      'Atlanta',
      'Augusta',
      'Columbus',
      'Savannah',
      'Athens',
      'Sandy Springs',
    ],
    'Hawaii': [
      'Honolulu',
      'Pearl City',
      'Hilo',
    ],
    'Idaho': [
      'Boise',
      'Meridian',
      'Nampa',
      'Idaho Falls',
    ],
    'Illinois': [
      'Chicago',
      'Aurora',
      'Naperville',
      'Joliet',
      'Rockford',
      'Springfield',
      'Elgin',
      'Peoria',
    ],
    'Indiana': [
      'Indianapolis',
      'Fort Wayne',
      'Evansville',
      'South Bend',
      'Carmel',
      'Fishers',
    ],
    'Iowa': [
      'Des Moines',
      'Cedar Rapids',
      'Davenport',
      'Sioux City',
      'Iowa City',
    ],
    'Kansas': [
      'Wichita',
      'Overland Park',
      'Kansas City',
      'Olathe',
      'Topeka',
    ],
    'Kentucky': [
      'Louisville',
      'Lexington',
      'Bowling Green',
      'Owensboro',
      'Covington',
    ],
    'Louisiana': [
      'New Orleans',
      'Baton Rouge',
      'Shreveport',
      'Lafayette',
      'Lake Charles',
    ],
    'Maine': [
      'Portland',
      'Lewiston',
      'Bangor',
    ],
    'Maryland': [
      'Baltimore',
      'Frederick',
      'Rockville',
      'Gaithersburg',
      'Bowie',
      'Annapolis',
    ],
    'Massachusetts': [
      'Boston',
      'Worcester',
      'Springfield',
      'Cambridge',
      'Lowell',
      'New Bedford',
    ],
    'Michigan': [
      'Detroit',
      'Grand Rapids',
      'Warren',
      'Sterling Heights',
      'Ann Arbor',
      'Lansing',
      'Flint',
    ],
    'Minnesota': [
      'Minneapolis',
      'Saint Paul',
      'Rochester',
      'Duluth',
      'Bloomington',
      'Brooklyn Park',
    ],
    'Mississippi': [
      'Jackson',
      'Gulfport',
      'Southaven',
      'Hattiesburg',
      'Biloxi',
    ],
    'Missouri': [
      'Kansas City',
      'St. Louis',
      'Springfield',
      'Columbia',
      'Independence',
      'Lee\'s Summit',
    ],
    'Montana': [
      'Billings',
      'Missoula',
      'Great Falls',
      'Bozeman',
    ],
    'Nebraska': [
      'Omaha',
      'Lincoln',
      'Bellevue',
      'Grand Island',
    ],
    'Nevada': [
      'Las Vegas',
      'Henderson',
      'Reno',
      'North Las Vegas',
      'Sparks',
    ],
    'New Hampshire': [
      'Manchester',
      'Nashua',
      'Concord',
    ],
    'New Jersey': [
      'Newark',
      'Jersey City',
      'Paterson',
      'Elizabeth',
      'Edison',
      'Woodbridge',
      'Trenton',
    ],
    'New Mexico': [
      'Albuquerque',
      'Las Cruces',
      'Rio Rancho',
      'Santa Fe',
    ],
    'New York': [
      'New York City',
      'Buffalo',
      'Rochester',
      'Yonkers',
      'Syracuse',
      'Albany',
      'New Rochelle',
    ],
    'North Carolina': [
      'Charlotte',
      'Raleigh',
      'Greensboro',
      'Durham',
      'Winston-Salem',
      'Fayetteville',
      'Cary',
    ],
    'North Dakota': [
      'Fargo',
      'Bismarck',
      'Grand Forks',
      'Minot',
    ],
    'Ohio': [
      'Columbus',
      'Cleveland',
      'Cincinnati',
      'Toledo',
      'Akron',
      'Dayton',
    ],
    'Oklahoma': [
      'Oklahoma City',
      'Tulsa',
      'Norman',
      'Broken Arrow',
      'Edmond',
    ],
    'Oregon': [
      'Portland',
      'Salem',
      'Eugene',
      'Gresham',
      'Hillsboro',
      'Bend',
    ],
    'Pennsylvania': [
      'Philadelphia',
      'Pittsburgh',
      'Allentown',
      'Reading',
      'Erie',
      'Harrisburg',
    ],
    'Rhode Island': [
      'Providence',
      'Warwick',
      'Cranston',
    ],
    'South Carolina': [
      'Charleston',
      'Columbia',
      'North Charleston',
      'Mount Pleasant',
      'Greenville',
    ],
    'South Dakota': [
      'Sioux Falls',
      'Rapid City',
      'Aberdeen',
    ],
    'Tennessee': [
      'Nashville',
      'Memphis',
      'Knoxville',
      'Chattanooga',
      'Clarksville',
      'Murfreesboro',
    ],
    'Texas': [
      'Houston',
      'San Antonio',
      'Dallas',
      'Austin',
      'Fort Worth',
      'El Paso',
      'Arlington',
      'Corpus Christi',
    ],
    'Utah': [
      'Salt Lake City',
      'West Valley City',
      'Provo',
      'West Jordan',
      'Orem',
      'Sandy',
    ],
    'Vermont': [
      'Burlington',
      'South Burlington',
      'Rutland',
    ],
    'Virginia': [
      'Virginia Beach',
      'Norfolk',
      'Chesapeake',
      'Richmond',
      'Newport News',
      'Alexandria',
      'Arlington',
    ],
    'Washington': [
      'Seattle',
      'Spokane',
      'Tacoma',
      'Vancouver',
      'Bellevue',
      'Kent',
      'Everett',
    ],
    'West Virginia': [
      'Charleston',
      'Huntington',
      'Morgantown',
    ],
    'Wisconsin': [
      'Milwaukee',
      'Madison',
      'Green Bay',
      'Kenosha',
      'Racine',
      'Appleton',
    ],
    'Wyoming': [
      'Cheyenne',
      'Casper',
      'Laramie',
    ],
  };

  static List<String> get states => statesCities.keys.toList();

  static List<String> citiesFor(String state) => statesCities[state] ?? [];
}
